Controllers/Admin/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PetFinderAPI.App_Data;
using PetFinderAPI.Models;

namespace PetFinderAPI.Controllers.Admin
{
    public class ProfilesController : Controller
    {
        // GET: Profiles
        private PetContext _db = new PetContext();
        public ActionResult index()
        {
            if (Session["user"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("admin/Auth/Login");
            }
        }

        public ActionResult MyProfile(int id)
        {
            if (Session["user"] != null)
            {
                var data = _db.Users.Where(s => s.Id == id).FirstOrDefault();

                ViewBag.user = data;

                return View(data);
            }
            else
            {
                return RedirectToAction("admin/Auth/Login");
            }
        }

        public ActionResult EditProfile(int id)
        {
            var data = _db.Users.Where(s => s.Id == id).FirstOrDefault();

            List<Role> roles = Models.Role.GetRoles();
            ViewBag.Roles = roles;
            data.Password = "";
            ViewBag.user = data;

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserName,DateOfBirth,Phone,Gender,Email,Password,New_Password,Avatar,Address,RoleId,IsActive")] User user)
        {
            //Debug.WriteLine("Path: " + file.ContentLength);
            HttpPostedFileBase ImageUrl = Request.Files["Avatar"];
            if (ImageUrl != null && ImageUrl.ContentLength > 0)
            {
                var fileName = Path.GetFileName(ImageUrl.FileName);
                Console.WriteLine("name" + fileName);
                var path = Path.Combine(Server.MapPath("~/Content/img/uploads/"), fileName);
                ImageUrl.SaveAs(path);
                user.Avatar = fileName;
            }


            if (ModelState.IsValid)
            {
                var data = _db.Users.Where(s => s.Id == user.Id).FirstOrDefault();

                if (!(String.IsNullOrEmpty(user.Password)))
                {

                    if (Crypto.VerifyHashedPassword(data.Password, user.Password))
                    {
                        user.Password = Crypto.HashPassword(user.New_Password);
                        _db.Entry(data).State = EntityState.Detached;
                        _db.Entry(user).State = EntityState.Modified;
                        _db.SaveChanges();

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        List<Role> roles2 = Models.Role.GetRoles();
                        ViewBag.Roles = roles2;
                        ViewBag.message = "Current password is fail!";
                        ViewBag.user = user;
                        return View(user);
                    }
                }

                //var data = _db.Users.Where(s => s.Id == user.Id).FirstOrDefault();
                try
                {
                    if (data != null)
                    {
                        _db.Entry(data).State = EntityState.Detached;
                    }
                    user.Password = data.Password;
                    //user.New_Password = data.Password;
                    _db.Entry(user).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");

                }
                catch (Exception e)
                {

                    Debug.WriteLine(" mess: " + e.Message);
                    return RedirectToAction("Index");

                }

            }
            List<Role> roles = Models.Role.GetRoles();
            ViewBag.Roles = roles;
            ViewBag.user = user;

            return View(user);
        }
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var user = _db.Users.Where(u => u.Id == id).First();
            _db.Users.Remove(user);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult GetUserID(int userID)
        {
            var user = _db.Users.Where(u => u.Id == userID).ToList();

            return Json(user, JsonRequestBehavior.AllowGet);
        }
    }


}

Views/Profiles/EditProfile.cshtml
@model PetFinderAPI.Models.User
@using System.Web.Mvc.Html;

@{ ViewBag.Title = "Users"; }
@section css {
    <link rel="stylesheet" type="text/css" href="~/Content/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css//bootstrap-datetimepicker.min.css">

}
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h4 class="page-title"> Edit Profile </h4>
            @if (ViewBag.message != "")
            {
                <span class="badge badge-danger">@ViewBag.message</span>}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            @using (Html.BeginForm("Edit", "Profiles", FormMethod.Post, new { enctype = "multipart/form-data" }
))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(m => m.Id)

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>User Name <span class="text-danger">*</span></label>
                            @Html.TextBoxFor(m => m.Id, new { @class = "form-control", @type = "hidden" })

                            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Email <span class="text-danger">*</span></label>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Date of Birth</label>
                            <div class="cal-icon">
                                @Html.TextBoxFor(m => m.DateOfBirth, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })

                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Phone </label>
                            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label>Address</label>
                                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })

                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group gender-select">
                            <label class="gen-label">Gender:</label>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    @Html.RadioButtonFor(m => m.Gender, "Male", new { Checked = "checked" }) Male
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    @Html.RadioButtonFor(m => m.Gender, "Female")  Female
                                </label>
                            </div>

                        </div>
                    </div>


                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Avatar</label>
                            <div class="profile-upload">
                                <div class="upload-img">
                                    @if (String.IsNullOrEmpty(ViewBag.user.Avatar))
                                    {
                                        <img id="avt" alt="" src="~/Content/img/user.jpg">

                                    }
                                    else
                                    {
                                        <img id="avt" alt="" src="~/Content/img/uploads/@ViewBag.user.Avatar">

                                    }
                                </div>
                                <div class="upload-input">
                                    @Html.TextBoxFor(m => m.Avatar, new { @class = "form-control", @type = "file" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="display-block">Role</label>
                            @foreach (var item in ViewBag.Roles)
                            {
                                <div class="form-check form-check-inline">
                                    <label class="form-check-label" for="doctor_inactive">
                                        @Html.RadioButtonFor(model => model.RoleId, (int)item.Id) @Html.Label((string)item.Name)
                                    </label>
                                </div>
                            }
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="display-block">Status</label>
                            <div class="form-check form-check-inline">
                                <label class="form-check-label" for="doctor_active">
                                    @Html.RadioButtonFor(m => m.IsActive, true, new { Checked = "checked" })  Active
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <label class="form-check-label" for="doctor_inactive">
                                    @Html.RadioButtonFor(m => m.IsActive, false)     Inactive
                                </label>
                            </div>
                        </div>
                    </div>
                 

                </div>



                <div class="m-t-20 text-center">
                    <button type="submit" name="submit" value="Update" class="btn btn-primary submit-btn">Update Profile</button>

                </div>}
        </div>
    </div>
</div>


@section scripts {

    <script src="~/Scripts/select2.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script>
    $(document).ready(function () {
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#avt').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]); // convert to base64 string
                }
            }

            $("#Avatar").change(function () {
                readURL(this);
            });
        });</script>

}